# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72f342e65050545efa08ee09197a2bd613dbd5aa7be65abe3d8d3d8613875eddc848faf4c349d4aa63bd0dbbd64847b86b7237f18cfa5fcb94268b6ef3b2d745

test:
  secret_key_base: c237f2c7eac43aa3ad264dffc9bbe130737058ddd7d4dd281f3f9b87624601430f0197446e86549f4094b4f4931c17c6770af7615f4392d93a3836b22f5d3f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
